from __future__ import annotations

from typing import Any


_REGIONAIS: tuple[dict[str, str], ...] = (
    {
        "codigo": "AC",
        "estado": "Acre",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO ACRE",
        "endereco": "Via Chico Mendes, n.º 2.896 - Triângulo Novo",
        "cidade_uf": "Rio Branco/AC",
        "cep": "69.906-302",
        "telefone": "(68) 3321-2491 (Recepção) / (68) 3321-2631 (Gabinete) / (68) 3321-2638 (NAOP)",
        "email": "cguac@cgu.gov.br",
        "superintendente": "Osmar Nilo de Jesus Lima Bezerra Neto",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Acre",
    },
    {
        "codigo": "AL",
        "estado": "Alagoas",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DE ALAGOAS",
        "endereco": "Rua José Soares Sobrinho, 119, sala 1101. Ed. Le Monde Empresarial. Bairro Jatiúca.",
        "cidade_uf": "Maceió/AL",
        "cep": "57036-640",
        "telefone": "(82) 4009-6350",
        "email": "cgual@cgu.gov.br",
        "superintendente": "Nelton Martins Yin Filho",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado de Alagoas",
    },
    {
        "codigo": "AP",
        "estado": "Amapá",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO AMAPÁ",
        "endereco": "Avenida Duque de Caxias nº 116, Centro",
        "cidade_uf": "Macapá/AP",
        "cep": "68.900-071",
        "telefone": "(96) 2101-9230 ramais: 9231 / 9232 / 9233 / 9234 / 9235 / 9236",
        "email": "cguap@cgu.gov.br",
        "superintendente": "José Iran Ataíde dos Santos",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Amapá",
    },
    {
        "codigo": "AM",
        "estado": "Amazonas",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO AMAZONAS",
        "endereco": "Rua Salvador, 440, Sala 705, Condomínio Soberane, Adrianópolis",
        "cidade_uf": "Manaus/AM",
        "cep": "69.057-040",
        "telefone": "(92) 2129-0163 / VOIP: 2163",
        "email": "cguam@cgu.gov.br",
        "superintendente": "Maria Esmeralda Rodrigues",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Amazonas",
    },
    {
        "codigo": "BA",
        "estado": "Bahia",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DA BAHIA",
        "endereco": "Avenida Jequitaia, s/n, Ministério da Fazenda, 2º andar, Sala 200 - Bairro: Comércio",
        "cidade_uf": "Salvador/BA",
        "cep": "40015-902",
        "telefone": "(71) 3254-5211 / VOIP: 9480",
        "email": "cguba@cgu.gov.br",
        "superintendente": "Romualdo Anselmo dos Santos",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado da Bahia",
    },
    {
        "codigo": "CE",
        "estado": "Ceará",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO CEARÁ",
        "endereco": "Rua Barão de Aracati, nº 909, 8º andar - Bairro Aldeota",
        "cidade_uf": "Fortaleza/CE",
        "cep": "60.115-081",
        "telefone": "(85) 3878-3800",
        "email": "cguce@cgu.gov.br",
        "superintendente": "Luiz Fernando Menescal de Oliveira",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Ceará",
    },
    {
        "codigo": "ES",
        "estado": "Espírito Santo",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO ESPÍRITO SANTO",
        "endereco": "Rua Pietrangelo de Biase, nº 56, 4º andar, Sala 404 - Centro",
        "cidade_uf": "Vitória/ES",
        "cep": "29.010-190",
        "telefone": "(27) 3202-4330 / (27) 99691-2872",
        "email": "cgues@cgu.gov.br",
        "superintendente": "José Euclides Cavalcante",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Espírito Santo",
    },
    {
        "codigo": "GO",
        "estado": "Goiás",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DE GOIÁS",
        "endereco": "Nona Avenida, Quadra A34, Lote 01/11, sala 216, Setor Leste Universitário",
        "cidade_uf": "Goiânia/GO",
        "cep": "74.603-010",
        "telefone": "(62) 3621-3151 / (62) 3621-3184",
        "email": "cgugo@cgu.gov.br",
        "superintendente": "Suzana Kroehling Rodrigues Ferreira",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado de Goiás",
    },
    {
        "codigo": "MA",
        "estado": "Maranhão",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO MARANHÃO",
        "endereco": "Avenida dos Holandeses, Lotes 8, 9 e 10 - Quadra K - Bairro Olho D'Água",
        "cidade_uf": "São Luís/MA",
        "cep": "65.065-180",
        "telefone": "(98) 3311-3476 / (98) 3311-3452",
        "email": "cguma@cgu.gov.br",
        "superintendente": "José Antônio de Carvalho Freitas",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Maranhão",
    },
    {
        "codigo": "MS",
        "estado": "Mato Grosso do Sul",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO MATO GROSSO DO SUL",
        "endereco": "Rua Pimenta Bueno, nº 139 - Bairro Amambai",
        "cidade_uf": "Campo Grande/MS",
        "cep": "79005-020",
        "telefone": "(67) 3303-4450",
        "email": "cgums@cgu.gov.br",
        "superintendente": "Leandro Marques de Sá",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Mato Grosso do Sul",
    },
    {
        "codigo": "MT",
        "estado": "Mato Grosso",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO MATO GROSSO",
        "endereco": "Avenida Vereador Juliano da Costa Marques, 99, Centro Político Administrativo (CPA)",
        "cidade_uf": "Cuiabá/MT",
        "cep": "78.049-937",
        "telefone": "(65) 2193-0437 / (65) 2193-0438",
        "email": "cgumt@cgu.gov.br",
        "superintendente": "Ricardo Placido Ribeiro",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Mato Grosso",
    },
    {
        "codigo": "MG",
        "estado": "Minas Gerais",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DE MINAS GERAIS",
        "endereco": "Rua Timbiras, nº 1.778, Lourdes",
        "cidade_uf": "Belo Horizonte/MG",
        "cep": "30.140-061",
        "telefone": "(31) 3888-3254",
        "email": "cgumg@cgu.gov.br",
        "superintendente": "Tânia Santiago Braga Oliveira",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado de Minas Gerais",
    },
    {
        "codigo": "PA",
        "estado": "Pará",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO PARÁ",
        "endereco": "Avenida Boulevard Castilhos Franca, n° 708 - 3º e 4º andar - Centro",
        "cidade_uf": "Belém/PA",
        "cep": "66.010-020",
        "telefone": "(91) 3205-8430 / (91) 3222-9446",
        "email": "cgupa@cgu.gov.br",
        "superintendente": "Lorena Pinho Morbach Paredes",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Pará",
    },
    {
        "codigo": "PB",
        "estado": "Paraíba",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DA PARAÍBA",
        "endereco": "Rua Barão do Abiaí, 73, 1º andar, Centro",
        "cidade_uf": "João Pessoa/PB",
        "cep": "58013-080",
        "telefone": "(83) 2108-3047 / (83) 2108-3046",
        "email": "cgupb@cgu.gov.br",
        "superintendente": "Rodrigo Márcio Medeiros Paiva",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado da Paraíba",
    },
    {
        "codigo": "PR",
        "estado": "Paraná",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO PARANÁ",
        "endereco": "Rua Marechal Deodoro, n° 555, 5º andar",
        "cidade_uf": "Curitiba/PR",
        "cep": "80.020-911",
        "telefone": "(41) 4501-7900",
        "email": "cgupr@cgu.gov.br",
        "superintendente": "Ricardo Jhum Fukaya",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Paraná",
    },
    {
        "codigo": "PE",
        "estado": "Pernambuco",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DE PERNAMBUCO",
        "endereco": "Rua General Joaquim Inácio, 830, Empresarial THE PLAZA, 19º andar, Ilha do Leite",
        "cidade_uf": "Recife/PE",
        "cep": "50.070-495",
        "telefone": "(81) 3134-8850",
        "email": "cgupe@cgu.gov.br",
        "superintendente": "Fábio da Silva Araújo",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado de Pernambuco",
    },
    {
        "codigo": "PI",
        "estado": "Piauí",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO PIAUÍ",
        "endereco": "Rua Mundinho Almeida, 105 - Noivos",
        "cidade_uf": "Teresina/PI",
        "cep": "64046-140",
        "telefone": "(86) 4009-4853 / (86) 4009-4850 / (86) 3215-8131",
        "email": "cgupi@cgu.gov.br",
        "superintendente": "Hélio Silva de Sousa Benvindo",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Piauí",
    },
    {
        "codigo": "RJ",
        "estado": "Rio de Janeiro",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO RIO DE JANEIRO",
        "endereco": "Avenida Presidente Antônio Carlos, nº 375, Ed. Palácio da Fazenda, 7º andar, Sala 711 - Centro",
        "cidade_uf": "Rio de Janeiro/RJ",
        "cep": "20.020-010",
        "telefone": "(21) 3805-3702 / (21) 3805-3707 / VOIP: (21) 2153-1902",
        "email": "cgurj@cgu.gov.br",
        "superintendente": "Carlos Henrique de Castro Ribeiro",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Rio de Janeiro",
    },
    {
        "codigo": "RN",
        "estado": "Rio Grande do Norte",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO RIO GRANDE DO NORTE",
        "endereco": "Avenida Hermes da Fonseca, nº 792 - Bairro Tirol",
        "cidade_uf": "Natal/RN",
        "cep": "59.020-095",
        "telefone": "(84) 3343-4732 / (84) 3343-4740 / (84) 3343-4747",
        "email": "cgurn@cgu.gov.br",
        "superintendente": "Rogério Vieira dos Reis",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Rio Grande do Norte",
    },
    {
        "codigo": "RS",
        "estado": "Rio Grande do Sul",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO RIO GRANDE DO SUL",
        "endereco": "Avenida Loureiro da Silva, nº 445, Ed. Ministério da Fazenda, 7° andar, Sala 704",
        "cidade_uf": "Porto Alegre/RS",
        "cep": "90.013-900",
        "telefone": "(51) 3533-5000 / (51) 3533-5004",
        "email": "cgurs@cgu.gov.br",
        "superintendente": "Dávison Wisniewski de Souza",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Rio Grande do Sul",
    },
    {
        "codigo": "RO",
        "estado": "Rondônia",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DE RONDÔNIA",
        "endereco": "Avenida Calama, nº 3.775 - Bairro da Embratel",
        "cidade_uf": "Porto Velho/RO",
        "cep": "76.820-781",
        "telefone": "(69) 2181-8251 / (69) 2181-8261 / (69) 2181-8263",
        "email": "cguro@cgu.gov.br",
        "superintendente": "Sônia Maria Mendes Moraes Silva",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado de Rondônia",
    },
    {
        "codigo": "RR",
        "estado": "Roraima",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DE RORAIMA",
        "endereco": "Avenida Capitão Ene Garcez, nº 1.024 - São Francisco",
        "cidade_uf": "Boa Vista/RR",
        "cep": "69.305-135",
        "telefone": "(95) 3212-5220 (Gabinete) / (95) 3212-5229 (Apoio) / (95) 3212-5223 (NAP)",
        "email": "cgurr@cgu.gov.br",
        "superintendente": "Alessandre Franklin Evangelista Pinagé",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado de Roraima",
    },
    {
        "codigo": "SC",
        "estado": "Santa Catarina",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DE SANTA CATARINA",
        "endereco": "Rua Conselheiro Mafra, 784 - Ático - Centro",
        "cidade_uf": "Florianópolis/SC",
        "cep": "88010-102",
        "telefone": "(48) 3298-7600 / 7607 (VOIP: 7600)",
        "email": "cgusc@cgu.gov.br",
        "superintendente": "Patrícia Maria Quintanilha de Moura",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado de Santa Catarina",
    },
    {
        "codigo": "SP",
        "estado": "São Paulo",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DE SÃO PAULO",
        "endereco": "Avenida Paulista, 1.804 - 18º Andar - Bela Vista",
        "cidade_uf": "São Paulo/SP",
        "cep": "01.310-922",
        "telefone": "(11) 3286-8200",
        "email": "cgusp@cgu.gov.br",
        "superintendente": "Armando de Nardi Neto",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado de São Paulo",
    },
    {
        "codigo": "SE",
        "estado": "Sergipe",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DE SERGIPE",
        "endereco": "Praça Graccho Cardoso, nº 44 - Bairro São José",
        "cidade_uf": "Aracaju/SE",
        "cep": "49.015-180",
        "telefone": "(79) 4009-2178",
        "email": "cguse@cgu.gov.br",
        "superintendente": "Bruno Fabiano Soares de Oliveira",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado de Sergipe",
    },
    {
        "codigo": "TO",
        "estado": "Tocantins",
        "nome_unidade": "CONTROLADORIA-GERAL DA UNIÃO NO ESTADO DO TOCANTINS",
        "endereco": "Quadra 103 Norte, Rua NO 05, Lote 13, Ed. Ranzi - Centro",
        "cidade_uf": "Palmas/TO",
        "cep": "77.001-020",
        "telefone": "(63) 3232-9350 (Geral) / (63) 3232-9354 (NAP) / (63) 3232-9355 (Gabinete)",
        "email": "cguto@cgu.gov.br",
        "superintendente": "Isa Mary de Carvalho Lima",
        "cargo_superintendente": "Superintendente da Controladoria Regional da União no Estado do Tocantins",
    },
)


def _with_contact_line(regional: dict[str, str]) -> dict[str, str]:
    return {
        **regional,
        "linha_endereco": (
            f'{regional["endereco"]} - {regional["cidade_uf"]} - CEP {regional["cep"]}'
        ),
        "linha_contato": (
            f'Tel. {regional["telefone"]} - {regional["email"]}'
        ),
    }


def list_nota_tecnica_regionais() -> list[dict[str, Any]]:
    return [_with_contact_line(regional).copy() for regional in _REGIONAIS]


def resolve_nota_tecnica_regional(codigo: str | None) -> dict[str, str]:
    normalized = str(codigo or "").strip().upper()
    if not normalized:
        raise RuntimeError("Regional emissora obrigatória para geração da Nota Técnica.")

    for regional in _REGIONAIS:
        if regional["codigo"] == normalized:
            return _with_contact_line(regional)

    raise RuntimeError(f"Regional emissora inválida para geração da Nota Técnica: {normalized}.")
