export const GENERIC_INDICATOR_DETAIL_KEYS = [
  'falecidos',
  'percentual_nao_comprovacao',
  'teto',
  'polimedicamento',
  'ticket_medio',
  'receita_paciente',
  'per_capita',
  'alto_custo',
  'vendas_rapidas',
  'volume_atipico',
  'recorrencia_sistemica',
  'dias_pico',
  'hhi_crm',
  'crms_irregulares',
];

export const INDICATOR_DETAIL_CONFIG = {
  falecidos: {
    title: 'Vendas p/ Falecidos',
    valueLabel: 'Percentual',
    benchmarkValueLabel: 'Percentual Falecidos',
    valueFormat: 'pct3',
    financialLabel: 'Valor para falecidos',
    formula: {
      description: 'Percentual do valor total comercializado associado a CPFs de falecidos.',
      numeratorLabel: 'Valor Falecidos',
      numeratorFormat: 'val',
      denominatorLabel: 'Total Comercializado',
      denominatorFormat: 'val',
      operator: '/',
      factor: 100,
    },
  },
  incompatibilidade_patologica: {
    title: 'Incompatibilidade Patológica',
    valueLabel: 'Percentual',
    benchmarkValueLabel: 'Incomp. Patológica',
    valueFormat: 'pct',
    financialLabel: 'Valor Incomp. Patológica',
    formula: {
      description: 'Percentual de vendas em desacordo com as diretrizes clínicas de patologia.',
      numeratorLabel: 'Valor Suspeito',
      numeratorFormat: 'val',
      denominatorLabel: 'Valor Monitorado',
      denominatorFormat: 'val',
      operator: '/',
      factor: 100,
    },
  },
  percentual_nao_comprovacao: {
    title: 'Percentual Não Comprovação',
    valueLabel: 'Percentual',
    benchmarkValueLabel: '% Não Comprovação',
    valueFormat: 'pct',
    financialLabel: 'Valor sem comprovação',
    formula: {
      description: 'Percentual do valor de vendas que não foram comprovadas.',
      numeratorLabel: 'Não Comprovado',
      numeratorFormat: 'val',
      denominatorLabel: 'Total Comercializado',
      denominatorFormat: 'val',
      operator: '/',
      factor: 100,
    },
  },
  teto: {
    title: 'Dispensação em Teto Máximo',
    valueLabel: 'Percentual',
    benchmarkValueLabel: 'Percentual em Teto Máximo',
    valueFormat: 'pct',
    formula: {
      description: 'Percentual do faturamento obtido acima do limite/teto máximo permitido.',
      numeratorLabel: 'Valor Acima do Teto',
      numeratorFormat: 'val',
      denominatorLabel: 'Valor Total',
      denominatorFormat: 'val',
      operator: '/',
      factor: 100,
    },
  },
  polimedicamento: {
    title: '4+ Itens por Autorização',
    valueLabel: 'Percentual',
    benchmarkValueLabel: '4+ Itens por Autorização',
    valueFormat: 'pct',
    formula: {
      description: 'Percentual financeiro das vendas associadas a autorizações contendo 4 ou mais itens.',
      numeratorLabel: 'Valor 4+ Itens',
      numeratorFormat: 'val',
      denominatorLabel: 'Faturamento Total',
      denominatorFormat: 'val',
      operator: '/',
      factor: 100,
    },
  },
  ticket_medio: {
    title: 'Valor do Ticket Médio',
    valueLabel: 'Ticket médio',
    valueFormat: 'val',
    formula: {
      description: 'Valor médio faturado por autorização emitida.',
      numeratorLabel: 'Faturamento Total',
      numeratorFormat: 'val',
      denominatorLabel: 'Total Autorizações',
      denominatorFormat: 'num',
      operator: '/',
      factor: 1,
    },
  },
  receita_paciente: {
    title: 'Faturamento Médio por Cliente',
    valueLabel: 'Valor',
    benchmarkValueLabel: 'Faturamento Médio por Cliente',
    valueFormat: 'val',
    formula: {
      description: 'Faturamento médio acumulado por cliente (paciente-mês ativo).',
      numeratorLabel: 'Faturamento Total',
      numeratorFormat: 'val',
      denominatorLabel: 'Clientes/Mês Ativos',
      denominatorFormat: 'num',
      operator: '/',
      factor: 1,
    },
  },
  per_capita: {
    title: 'Venda Per Capita Mensal',
    valueLabel: 'Valor',
    benchmarkValueLabel: 'Venda Per Capita Mensal',
    valueFormat: 'val',
    formula: {
      description: 'Valor de venda proporcional à população do município.',
      numeratorLabel: 'Faturamento Total',
      numeratorFormat: 'val',
      denominatorLabel: 'Denominador Per Capita',
      denominatorFormat: 'num',
      operator: '/',
      factor: 1,
    },
  },
  alto_custo: {
    title: 'Medicamentos de Alto Custo',
    valueLabel: 'Percentual',
    benchmarkValueLabel: 'Medicamentos de Alto Custo',
    valueFormat: 'pct',
    formula: {
      description: 'Proporção de vendas de medicamentos de alto custo no faturamento total.',
      numeratorLabel: 'Valor Alto Custo',
      numeratorFormat: 'val',
      denominatorLabel: 'Faturamento Total',
      denominatorFormat: 'val',
      operator: '/',
      factor: 100,
    },
  },
  vendas_rapidas: {
    title: 'Vendas Rápidas (<60s)',
    valueLabel: 'Percentual',
    benchmarkValueLabel: 'Vendas Rápidas',
    valueFormat: 'pct',
    formula: {
      description: 'Proporção de vendas realizadas em intervalo menor que 60 segundos.',
      numeratorLabel: 'Valor Vendas Rápidas',
      numeratorFormat: 'val',
      denominatorLabel: 'Faturamento Total',
      denominatorFormat: 'val',
      operator: '/',
      factor: 100,
    },
  },
  volume_atipico: {
    title: 'Aumento atípico de vendas',
    valueLabel: 'Índice',
    valueFormat: 'dec',
    formula: {
      description: 'Média do excesso de crescimento percentual nos semestres comparáveis.',
      numeratorLabel: 'Excesso Crescimento Pct',
      numeratorFormat: 'num',
      denominatorLabel: 'Semestres Comparáveis',
      denominatorFormat: 'num',
      operator: '/',
      factor: 1,
    },
  },
  recorrencia_sistemica: {
    title: 'Recorrência Sistêmica',
    valueLabel: 'Percentual',
    valueFormat: 'pct',
    formula: {
      description: 'Proporção de vendas recorrentes sistemáticas sob suspeita de fracionamento.',
      numeratorLabel: 'Valor Recorrência',
      numeratorFormat: 'val',
      denominatorLabel: 'Valor Total Renovações',
      denominatorFormat: 'val',
      operator: '/',
      factor: 100,
    },
  },
  dias_pico: {
    title: 'Concentração em Dias de Pico',
    valueLabel: 'Percentual',
    valueFormat: 'pct',
    formula: {
      description: 'Proporção do faturamento concentrado nos 3 dias de maior volume do mês.',
      numeratorLabel: 'Valor Top 3 Dias',
      numeratorFormat: 'val',
      denominatorLabel: 'Faturamento Total',
      denominatorFormat: 'val',
      operator: '/',
      factor: 100,
    },
  },
  hhi_crm: {
    title: 'Concentração de CRMs (HHI)',
    valueLabel: 'HHI',
    benchmarkValueLabel: 'HHI CRM',
    valueFormat: 'dec',
    formula: {
      description: 'Índice de concentração de prescritores (Herfindahl-Hirschman Index).',
      numeratorLabel: 'HHI Ponderado',
      numeratorFormat: 'num',
      denominatorLabel: 'HHI Valor Total',
      denominatorFormat: 'num',
      operator: '/',
      factor: 1,
    },
  },
  crms_irregulares: {
    title: 'Faturamento CRMs Irregulares',
    valueLabel: 'Percentual',
    benchmarkValueLabel: 'Faturamento CRMs Irregulares',
    valueFormat: 'pct',
    formula: {
      description: 'Percentual do faturamento associado a prescrições de CRMs com irregularidades.',
      numeratorLabel: 'Valor CRMs Irregulares',
      numeratorFormat: 'val',
      denominatorLabel: 'Valor Total Prescrito',
      denominatorFormat: 'val',
      operator: '/',
      factor: 100,
    },
  },
};
